import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.nav}></nav>
      <main className={styles.main}>
        <section className={styles.hero}>
          <div className={styles.heroInfo}>
            <h1>I&apos;m Bao Huynh</h1>
            <p>Fullstack developer</p>
          </div>
        </section>
      </main>
    </>
  );
};

export default Home;
